SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `multiplicacao`.`Discipulo` DROP COLUMN `lider` , ADD COLUMN `lider` INT(11) NULL DEFAULT NULL  AFTER `nivel` , 
  ADD CONSTRAINT `fk_Discipulo_Discipulo`
  FOREIGN KEY (`lider` )
  REFERENCES `multiplicacao`.`Discipulo` (`id` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `fk_Discipulo_Discipulo` (`lider` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
